### ISSUE TITLE
badges in readme are broken

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/acpaas-ui_angular#114]
## Describe the bug

The badges in the readme are broken.

## To Reproduce

1. Go to https://github.com/digipolisantwerp/acpaas-ui_angular
2. See the badges in the ecosystem part of the readme
3. they show "invalid response data" errors

**Comment by gerturo** [comment]
Picked up by ACPaaS frontend team

**Comment by TriangleJuice** [comment]
Fixed.
