### ISSUE TITLE
Modal closes on autocomplete select

### ISSUE THREAD

**Issue by NK-Hertz** [digipolisantwerp/acpaas-ui_angular#122]
## Describe the bug
Using aui-autocomplete inside modal, on selecting any autocomplete option the modal closes.

## To Reproduce
1. Implement aui-autocomplete in aui-modal
2. Click on autocomplete
3. Select any option from autocomplete results
4. Modal closes

## Expected behavior
Modal should stay open/be unaffected by aui-autocomplete actions/

**Comment by TriangleJuice** [comment]
Fixed in #169 (v3.0.0)
