### ISSUE TITLE
Suggested FooterModule html doesn't work

### ISSUE THREAD

**Issue by kimjanssens** [digipolisantwerp/acpaas-ui_angular#138]
## Describe the bug

Footer component: using the suggested html doesn't work

## To Reproduce

1. Install Footer Module as described
2. Footer isn't printed

## Expected behavior

Footer should have been generated

## OS (please complete the following information):

 - Chrome

## Additional context

Removing `<div class="u-margin-bottom u-margin-top">` wrapper fixed the issue

**Comment by TriangleJuice** [comment]
Can we get a bit more information on this one, as this component is used (and working) in dozens of other applications. Thanks in advance!

**Comment by TriangleJuice** [comment]
Closed because after a month we still didn't get any response.
