### ISSUE TITLE
Pagination shows too many page numbers

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/acpaas-ui_angular#144]
## Describe the bug

When you have a lot of pages and you pass currentPage >= 5 as a string, the pagination renders with far too many number buttons.

The bug is introduced on this line: https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/packages/pagination/lib/src/pagination/components/pagination/pagination.component.ts#L69

When currentPage is a string, the slice command ends up converting to at least "5" + 1, or page 51. 

## Workaround

The application that renders the aui-pagination can pass currentPage as a number instead of a string. The bug does not occur in that case.

## Screenshots

<img width="747" alt="pagination-bug" src="https://user-images.githubusercontent.com/2686747/60027545-f53da300-969d-11e9-9d29-c34bb90461da.png">

**Comment by TriangleJuice** [comment]
Fixed by #145
