### ISSUE TITLE
Using ngx-components with angular 7 produces peerdependencies warnings

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/acpaas-ui_angular#147]
## Describe the bug

When setting up an angular 7 or 8 project with ngx-components errors are shown by npm:

`requires a peer of @angular/core@^6.1.0 but none is installed`

This is due to the use of `^` in the peerdependencies. Instead `>` should be used, or the use of the double pipe to signify that multiple major releases are supported.

## Expected behavior

No peerdependencies warnings if a compatible angular version is used.

**Comment by tom-odb** [comment]
If we can guarantee that the release will work with other major angular releases, this is fine. Otherwise, I don't see any harm in showing the warning, making it clear that this release is supported and has been confirmed working in v6. Any other version is "use at your own risk" imo.

**Comment by jsebrech** [comment]
Well, v7 is supported as well, so showing a warning in that case is not correct.
