### ISSUE TITLE
Build error after installing npm package

### ISSUE THREAD

**Issue by nickcuypers** [digipolisantwerp/acpaas-ui_angular#178]
## Describe the bug
Build error: 
ERROR in node_modules/@acpaas-ui/ngx-components/calendar/acpaas-ui-ngx-components-calendar.d.ts.CalendarMonthComponent.html(4,83): Argument of type 'unknown[]' is not assignable to parameter of type 'string'.

## To Reproduce

1. npm i @acpaas-ui/ngx-components
2. ng build --prod --output-hashing none && del-cli ./wwwroot/index.html
3. See error

## Expected behavior

no build error

## Screenshots

![image](https://user-images.githubusercontent.com/22317343/71885170-19dd0200-313a-11ea-991d-4251e11b5d41.png)

## OS (please complete the following information):

 - OS: windows 10
 - Version Angular version 8

**Comment by TriangleJuice** [comment]
Fixed by #183
