### ISSUE TITLE
Datepicker with blank year or month gives a date in 2001

### ISSUE THREAD

**Issue by sander-c** [digipolisantwerp/acpaas-ui_angular#179]
## Describe the bug

When filling next dates in the datepicker
"08/__/____" gives "2001-07-31T22:00:00.000Z",
"08/05/____" gives ""2001-05-07T22:00:00.000Z""
while you should get the error 'invalid date'

## To Reproduce

You can test it in the docs: https://digipolisantwerp.github.io/acpaas-ui_angular/modules/forms/datepicker

## Expected behavior

Should give a error message if the date isn't filled in completely

**Comment by TriangleJuice** [comment]
Fixed by #183
