### ISSUE TITLE
Use stateful components in table cell

### ISSUE THREAD

**Issue by Marti2203** [digipolisantwerp/acpaas-ui_angular#18]
## Is your feature request related to a problem? Please describe.
We have a table that has an Inline edit component but the component loses its state when clicking, because a new one replaces it. I would like not to make special logic which will spaghettify our software production line.

## Describe the solution you'd like
Either a flag to the table or change the functionality so that it does not create a new instance of the component.

## Describe alternatives you've considered
Manually tweaking the code of the table component which is being done for now.

## Additional context
I am from Codific

**Comment by tom-odb** [comment]
Can you provide a small repro (e.g. on stackblitz or codesandbox)?

**Comment by Marti2203** [comment]
By the way, I need a VPN to install the components, will this be changed? https://codesandbox.io/s/p7rm2nxpkm

**Comment by Marti2203** [comment]
This is with the fix https://codesandbox.io/s/9yw38x820r in the Table Cell Component

**Comment by tom-odb** [comment]
vpn is only required for the "old" components hosted on the private nexus repo, the components from this repo are hosten on npmjs and should be publicly available

I think a better fix would be to verify the component input has changed in the `ngOnChanges`:
https://codesandbox.io/s/j42rz3zkmy?module=%2Fsrc%2Ftable%2Ftable-cell%2Ftable-cell.component.ts

feel free to open up a pr with this fix
