### ISSUE TITLE
Add Angular 6+ packages as peerDependencies

### ISSUE THREAD

**Issue by Marti2203** [digipolisantwerp/acpaas-ui_angular#19]
## Is your feature request related to a problem? Please describe.
We are using Angular 6.0 and are getting a lot of warnings for incorrect peer dependencies

## Describe the solution you'd like
Update the version requirements

## Describe alternatives you've considered
Changing the code by hand.

## Additional context
I am from Codific

**Comment by tom-odb** [comment]
Which dependencies are giving you issues? Feel free to update them in a pr.

**Comment by Marti2203** [comment]
I am not having issues, everything is working without a problem. It is just annoying and Angular 6 has speed improvements.

**Comment by tom-odb** [comment]
We do depend on angular 6+, any warnings about versions lower than 6 are probably thrown by other packages you have installed.
On a clean install, the only warnings I see are missing peer dependencies for angular@^6.0.0 (from ng2-ckeditor) which seems al right to me.

We should however add the angular packages as peer dependencies on the root of the package as well.

**Comment by TriangleJuice** [comment]
Resolved in #40
