### ISSUE TITLE
Time picker limits the functionality of text fields

### ISSUE THREAD

**Issue by nickcuypers** [digipolisantwerp/acpaas-ui_angular#204]
## Describe the bug

Time picker limits the functionality of text fields.

## To Reproduce

If the component is selected by clicking on the clock icon, a time is chosen, and there's clicked outside the component, after that if you want to select a text field, it will select the text field but you cannot type anything.
So focus changes but typing is impossible.
This can only be solved by selecting the time picker component again, but this time clicking on the time itself, then outside the component and selecting the text field again, now you can type.

**Comment by TriangleJuice** [comment]
I cannot reproduce the bug the way you described it. Can you maybe give a working example of the bug in action? Can you also check if the same bug is present in our styleguide? https://digipolisantwerp.github.io/acpaas-ui_angular/modules/forms/timepicker
