### ISSUE TITLE
Can't resolve '@acpaas-ui/js-notification-store' in ...

### ISSUE THREAD

**Issue by TomVanDenBroeck** [digipolisantwerp/acpaas-ui_angular#44]
## Describe the bug
An existing bug in the acpaas-ui_js repo also occurs in the acpaas-ui_angular repo when using the `notification-service` of the @acpaas-ui/ngx-components.

`https://github.com/digipolisantwerp/acpaas-ui_js/issues/3`

## OS (please complete the following information):

 - Device: HP laptop
 - OS: WIN10
 - Browser Chrome
 - Version N/A

**Comment by gerturo** [comment]
Picked up by ACPaaS frontend team

**Comment by lievenvg** [comment]
Issue is solved in https://github.com/digipolisantwerp/acpaas-ui_js/ with `@acpaas-ui/js-notification-store@1.0.1`
