### ISSUE TITLE
error importing AutoCompleteModule with ng serve --aot

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/acpaas-ui_angular#57]
## Describe the bug

When importing the autocomplete component in a project that uses the --aot flag for ng serve the following error is produced:

```
ERROR in : Unexpected value 'AutoCompleteModule 
in C:/digipolis/prototypes/my-app/node_modules/@acpaas-ui/ngx-components/forms/forms.d.ts' 
imported by the module 'AppModule in C:/digipolis/prototypes/my-app/src/app/app.module.ts'. 
Please add a @NgModule annotation.
```

## To Reproduce

1. Follow the getting started instructions to create a new project
2. Import AutoCompleteModule in app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AutoCompleteModule} from '@acpaas-ui/ngx-components/forms';
import { AppComponent } from './app.component';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AutoCompleteModule
  ],
```

3. Add `<aui-auto-complete>` to app.component.html as per the example
4. Run ng serve --aot
5. See the error

## Expected behavior

ng serve --aot flag should be supported

**Comment by jsebrech** [comment]
Problem also appears with other components and with the styleguide.

**Comment by gerturo** [comment]
Welke andere componenten hebben nog dit probleem?

**Comment by jsebrech** [comment]
Bij FooterModule kreeg ik een andere foutmelding (bij het binnentrekken in de app.module.ts):
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'layout' in 'C:\digipolis\prototypes\my-app\src\app'
```

Bij AvatarModule was er een analoge foutmelding als FooterModule. Ik vermoed dus dat het voor alle componenten is.
