### ISSUE TITLE
Examples are really CPU intensive (while they shouldn't)

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/acpaas-ui_angular#62]
## Describe the bug

Certain components become really unresponsive after using them for a (short) while.

## To Reproduce

1. Go to the online styleguide
2. Navigate to the "Forms" examples
3. Try to use some examples

## Expected behavior

Components should be smooth as butter ;-)

## OS (please complete the following information):

 - Device: MacBook Pro (Retina, 15-inch, Early 2013)
 - OS: macOS 10.13.6 (High Sierra)
 - Browser: any
 - Version: all

## Additional context

It seems that the unresponsiveness has to do something with components that use two-way binding.

**Comment by jsprds** [comment]
Problem is probably due to a scroll event of the Headroom package. Daarnaast heb ik ook nog performance problemen gemerkt bij de auto-complete. Furthermore, the examples are quite performant when I disable the header.

**Comment by lievenvg** [comment]
The culprit seems to be the `code-snippet` component that's excessively checking for `pre` tags.
