### ISSUE TITLE
Can't use "Context" component without redux

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/acpaas-ui_angular#63]
## Describe the bug

When implementing the "Context" component in my app that doesn't use redux, I get the error `Module not found: Error: Can't resolve '@angular-redux/store' in '/Users/trianglejuice/Desktop/context/node_modules/@acpaas-ui/ngx-components/context/fesm5' `

## To Reproduce

1. Create an empty app
2. In `app.module.ts`:

```
import { ContextModule } from '@acpaas-ui/ngx-components/context';
[...]
  imports: [
    BrowserModule,
    ContextModule.forRoot({
      useTitleSuffix: true,
      extendTitle: true,
      titleDelimiter: '|',
      defaults: {
        title: 'test',
      },
    }),
  ],
[...]
```
3. Run the app

## Expected behavior

A working app.

## Screenshots

N/A

## OS (please complete the following information):

 - Device: MacBook Pro (Retina, 15-inch, Early 2013)
 - OS: macOS 10.13.6 (High Sierra)
 - Browser: all
 - Version: any

## Additional context

-

**Comment by tom-odb** [comment]
store should be exported separately -> remove from index, add index in store so it can be imported from `@acpaas-ui/ngx-components/context/store`

**Comment by tom-odb** [comment]
store should be exported separately -> remove from index, add index in store so it can be imported from `@acpaas-ui/ngx-components/context/store` (cfr notifications)
