### ISSUE TITLE
Context module not correctly implemented in Styleguide

### ISSUE THREAD

**Issue by lievenvg** [digipolisantwerp/acpaas-ui_angular#92]
## Describe the bug

The default Styleguide title is replaced by '| Context Module'.

## To Reproduce

1. Open the (acpaas-ui_angular Styleguide)[https://digipolisantwerp.github.io/acpaas-ui_angular/] in a tabbed browser.

## Expected behavior

The title in the tab of the browser should be 'Acpaas UI | Angular Modules' and it should update to  'Acpaas UI | Context Module' when you open the 'Context' example in de sidebar.

## Screenshots

<img width="370" alt="tabbed browser screenshot" src="https://user-images.githubusercontent.com/10128807/48697795-c631f100-ebe5-11e8-964c-0e818a0e9733.png">

## OS (please complete the following information):

Device: MacBook Pro (Retina, 13-inch, Late 2013)
OS: macOS High Sierra (Version 10.14.1)
Browser: All browsers

**Comment by TriangleJuice** [comment]
Fixed in #170 (v3.0.0)
