### ISSUE TITLE
Error in console when running the utils>window example

### ISSUE THREAD

**Issue by TomVanDenBroeck** [digipolisantwerp/acpaas-ui_angular#99]
## Describe the bug

Console error when clicking on 'Window' in the 'Utils'

## To Reproduce

Go to 'https://digipolisantwerp.github.io/acpaas-ui_angular/modules/utils/window'

## Expected behavior

works in local version!

## OS (please complete the following information):

 - Device: MacBook Air
 - OS: macOS Mojave
 - Browser: All

## Screenshots

![screenshot 2018-12-11 at 13 47 55](https://user-images.githubusercontent.com/14332304/49801831-8de88300-fd4b-11e8-8243-52b3a6842c77.png)

**Comment by lievenvg** [comment]
Fixed with PR #100
